repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
        exclude: '.*\.(xml|xslt|txt|xsd)$'
      - id: end-of-file-fixer
        exclude: '.*\.(xml|xslt|txt|xsd)$'
      - id: check-merge-conflict

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1  # Use the latest version
    hooks:
      - id: flake8
        args: [--max-line-length=88]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0  # Use the latest version
    hooks:
      - additional_dependencies: [types-pytz==2024.1.0.20240417]
        id: mypy

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0  # Use the latest version
    hooks:
      - id: python-check-blanket-noqa

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest --cov=gib_esu.models --cov=gib_esu.services --cov=gib_esu.helpers --cov-report=term-missing
        language: system
        stages: [push]
        types: [python]
        pass_filenames: false
        always_run: true
